services:
  python-app:
    container_name: python-app
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    networks:
      - app-network

  react-app:
    container_name: react-app
    build:
      context: ./front/frontend
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
    depends_on:
      - python-app
    networks:
      - app-network
    links: 
      - python-app

networks:
  app-network:
    driver: bridge