services:
  python-app:
    build:
      context: front
      dockerfile: front/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  react-app:
    build:
      context: front/frontend
      dockerfile: front/frontend/Dockerfile.react
    ports:
      - "3000:3000"
    depends_on:
      - python-app