services:
  python-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./front:/app

  react-app:
    build:
      context: ./front/frontend
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
    depends_on:
      - python-app