services:
  python-app:  
    container_name: python-app
    build:    
      context: ./back
      dockerfile: Dockerfile  
    restart: on-failure
    ports:    
      - "8000:8000"

  react-app:
    build:
      context: ./front/frontend
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
    depends_on:
      - python-app