services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
    depends_on:
      - python-app